apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: memos-pvc
  namespace: memos 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi 
