apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage 
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/DidZ0
  services.yaml: |
    - Hypervisors:
        - Tiny:
            href: https://192.168.1.241:8006
            icon: proxmox.png
            description: Tiny server 
        - Micro:
            href: https://192.168.1.51:8006
            icon: proxmox.png
            description: Micro server 
        - Huge:
            href: https://192.168.1.250:8006
            icon: proxmox.png
            description: Huge server 

    - Network:
        - Adguard:
            href: http://192.168.1.104
            icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/adguard-home.png
            widget:
              type: adguard
              url: http://192.168.1.104
              username: bomal
              password: 1BudokaOne1303
        - UptimeKuma:
            href: https://uptime.bomal.cloud
            icon: uptime-kuma.png 
            widget:
              type: uptimekuma
              url: https://uptime.bomal.cloud 
              slug: homelab
    - Media:
        - Jellyfin:
            icon: jellyfin.png
            href: https://jellyfin.local.bomal.cloud/
            description: Netflix clone 
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
      #- longhorn:
      #  expanded: true
      #  total: true
      #  labels: true
      #  nodes: true
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
